## Numpy Version

In [3]:
import numpy as np
import pandas as pd

In [4]:
np.__version__
# 밑에 버전까지 같이 쓰면 항상 밑에 쓴 버전만 나옴. 둘다 따로 써줘야 버전을 확인가능. 

'1.1.5'

In [5]:
pd.__version__

'1.1.5'

In [1]:
!pip list

Package             Version
------------------- -------------------
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.3.0
backcall            0.2.0
bleach              3.3.0
certifi             2020.12.5
cffi                1.14.5
colorama            0.4.4
cycler              0.10.0
decorator           5.0.6
defusedxml          0.7.1
entrypoints         0.3
importlib-metadata  3.10.0
ipykernel           5.3.4
ipython             7.16.1
ipython-genutils    0.2.0
ipywidgets          7.6.3
jedi                0.17.0
Jinja2              2.11.3
joblib              1.0.1
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.12
jupyter-console     6.4.0
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.0
kiwisolver          1.3.1
MarkupSafe          1.1.1
matplotlib          3.3.4
mistune             0.8.4
nbclient            0.5.3
nbconvert           6.0.7
nbformat            5.1.3
nest-asyncio        1.5.1
notebook    

## ndarray 생성

In [7]:
arr = np.array([1,2,3,4], dtype = int)

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.shape # 4행

(4,)

In [11]:
# 1차원 리스트
myList = [1,2,3,4] # python에 list 타입으로 데이터를 집어 넣어 줌. python 에 먼저 list 생성하고
arr = np.array(myList, dtype=float) # numpy arr 에서는 그 리스트를 바탕으로 arrary 생성
#. shape 찍을려면 np arrary 로 리스트를 넣어야 함. 
# 사람들이 헷갈리는 부분: numpy 로 arrary 리스트 넣어야 shape을 찍을 수 있는데 , 파이썬에서 리스트 만들고 shape을 찍으려 함. 

In [12]:
arr

array([1., 2., 3., 4.])

In [13]:
# 퀴즈
myList = [1.3, 2.3,3.3,4.3]
arr = np.array(myList, dtype = int)

In [14]:
arr # 형변환이 일어남 알아서. 워닝도 안주기 때문에 확인해야 함. 짤라버림. 1차원리스트에서는 형변환을 안시켜도 알아서 일어남. 

array([1, 2, 3, 4])

In [16]:
# 2차원 리스트
myList2 = [
    [1,2,3,4],
    [5,6,7,8]
]

In [17]:
myList2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr = np.array(myList2)

In [19]:
arr.shape

(2, 4)

In [20]:
type(arr) # dtype = int 설정안했는데 안의 값이 int 인경우 알아서 int 으로 나옴
# 만약 소숫점 1개라도 들어가면 전체가 float 로 들어감. 

numpy.ndarray

In [22]:
myList = [1,3.14,'hello','1234']

In [23]:
myList

[1, 3.14, 'hello', '1234']

In [24]:
arr = np.array(myList)

In [25]:
arr # 전부 문자열로 바뀜. 최대한 왜곡시키지 않고 받아들이는 방법.
#dtype = '<U5' : 가장 긴길이가 5글자라서 나옴. 

array(['1', '3.14', 'hello', '1234'], dtype='<U32')

In [26]:
arr[0]+arr[1]

'13.14'

In [27]:
float(arr[0]+arr[1]) # 문자끼리 더한후에 형변환 한 걸로 나옴. 

13.14

In [28]:
float(arr[0])+float(arr[1]) # 각 따로 형변환 먼저 시키고 더해야 소수가 나옴

4.140000000000001

## 슬라이싱(Slicing)

배열을 부분 선택

#### 1차원 배열의 부분 선택

In [29]:
arr = np.array([0,1,2,3,4,5,6,7,8,9]) # 시작번호는 0번부터 시작한다. 
arr.shape

(10,)

In [30]:
arr[2]

2

In [31]:
arr[10] # Index 범위 지정한 것을 넘어갔구나! IndexError: 범위를 벗어남.

IndexError: index 10 is out of bounds for axis 0 with size 10

In [33]:
arr[-1] # 뒤에서 첫번째. 양수로 시작시 0이 첫번째인데 뒤에선 -1 이 끝에서 첫번째임.  

9

In [34]:
# 뒤에서 거꾸로 0을 가지고 오고 싶다면 -10
arr[-10]

0

In [35]:
arr[-11] # 이것도 범위 이상으로는 허용하지 않음. 

IndexError: index -11 is out of bounds for axis 0 with size 10

#### 2차원 배열의 부분 선택

In [36]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [37]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr1d = np.array(arange(12))

NameError: name 'arange' is not defined

In [39]:
arr1d = np.array(np.arange(12))

In [40]:
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
arr1d.reshape(-1,4) # 시작이 0인것 그대로 시작. 근데 원하는건 1부터 나오길 원함. 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
# np.arange(12): 시작값은 0이고(생략), 종료조건이 12 미만인경우
# np.arange(1,13): 시작값이 1이고, 종료조건 13 미만
arr1d = np.array(np.arange(1,13)).reshape(3,4)

In [43]:
arr1d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr2d[0,2] # 행과 열 0부터 시작됨.
# 0행의 2열에 있는 거 가져와라.

3

In [45]:
arr2d[2,2]

11

In [46]:
arr1d = np.array(np.arange(1,13))

In [47]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
# 2-12 까지만
# 시작값 : 종료값 ( 생략하면 끝까지)
arr1d[1:] # 0번 생략, 1번부터 끝까지

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
# 시작값(이상) : 종료값 (index 값의 미만. 자기를 포함하지 않음.)
arr1d[1:10] # 10미만이라 10까지 나온것임. 여기서 10이 인덱스 9번자리. 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr1d[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
arr1d[:-1] # 뒤에있는 것 하나를 빼자. 12 빠지는 것임

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
arr1d[:-2] # 뒤에서 두개를 빼자. 12, 11 빠짐 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr1d[:0]

array([], dtype=int32)

In [54]:
# 한 행 지정한 뒤 모두 가져오는 경우
# 행, 열 = (: 모든 열)

arr2d[1,:] # 1행의 모든 것을 가져와라. 

array([5, 6, 7, 8])

In [55]:
arr2d[1,:].shape # 4행 

(4,)

In [56]:
arr2d[:,2]

array([ 3,  7, 11])

In [57]:
arr2d[1,:].shape

(4,)

In [58]:
arr2d[:2,1:3]

array([[2, 3],
       [6, 7]])

In [59]:
# 5x5 배열, 1부터 1씩 증가하는 배열 (1-25)
# 12,13,14 / 17,18,19 / 22,23,24 가져오기 (3,4,5행의 각 열 2,3,4열임)
my2darr = np.array(np.arange(1,26)).reshape(5,5)

In [60]:
my2darr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
my2darr[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

## Fancy Indexing

범위가 아닌 특정 index값을 선택해서 추출하고 싶을 때

In [62]:
# 1차원의 Fancy indexing
myArr = np.array(np.arange(1,10))

In [63]:
myArr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
idx = [0,2,4] # 0,2,4번 의 인덱싱. (1, 3, 5 임)

In [68]:
myArr[idx]

array([1, 3, 5])

In [69]:
# 2차원의 Fancy indexing
my2dArr = np.array(np.arange(1,13)).reshape(3,4)
my2dArr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
# 0번 과 1번 행 가져오기 위한 인덱스 먼저 만들기
idx = [0,2,3]

In [74]:
my2dArr[:2,idx]

array([[1, 3, 4],
       [5, 7, 8]])

## Boolean Indexing - 필터 조건 활용케이스가 가장 많음

조건 필터링을 통해서 Boolean 값을 이용한 색인

In [77]:
arr = np.array(np.arange(1,8))
arr

array([1, 2, 3, 4, 5, 6, 7])

In [79]:
arr2d = np.array(np.arange(1,13)).reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
myTrueFalse = [True, False, True, False, False, False, False]

In [84]:
arr[myTrueFalse]

array([1, 3])

In [90]:
myTrueFalse = [[True, False, True, False],[True, False, True, False],[False,False,False,False]]

In [91]:
TrueFalse = np.array(myTrueFalse)

In [93]:
arr2d[TrueFalse]

array([1, 3, 5, 7])

In [94]:
# 조건 필터
arr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [96]:
TrueFalse = arr2d > 2

In [97]:
arr2d[TrueFalse]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [98]:
arr2d[arr2d>2] # 조건 필터구나! true 에 해당하는 데이터만 가져온다. 

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
arr2d[arr2d<5]

array([1, 2, 3, 4])

## arange 란?

array + range = arange

In [104]:
arr = [1,2,3,4,5,6,7,8,9,10]

In [105]:
# start (이상), stop(미만)
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
# 키워드를 사용해서 순서없이
arr = np.arange(start=1, stop = 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
# (start, stop, step)
# 홀수만 생성
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [110]:
arr = np.arange(start=1, step=2, stop=11)
arr

array([1, 3, 5, 7, 9])

### range (numpy 와는 상관없는 python 문법)

In [111]:
# range 는 조건을 말할 뿐 아직 숫자가 생성 X
test = range(1,11)
print(test)

range(1, 11)


In [112]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [113]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9


## 1차원 정렬

In [114]:
arr = np.array([1,10,5,8,2,4,3,6,7,9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

In [115]:
np.sort(arr) # 정렬해서 출력. array 자체를 바꿔서 저장해서 출력하는게 아님. 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

In [117]:
# 만약 바꾸고 싶다면
mysort = np.sort(arr)
mysort #ascending 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
# 내림차순 정렬일 경우 옵션값에 -1을 지정한다. 
np.sort(arr)[::-1] # desc

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## 2차원 정렬

In [123]:
arr2d = np.array([[5,6,7,8],
                 [4,3,2,1], 
                 [10,9,12,11]])

In [121]:
arr2d.shape

(3, 4)

In [124]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [125]:
# axis 축이 행인지, 열인지를 가리킨다.
# axis=1 하면 같은 행안에서 정렬이 된다.
np.sort(arr2d, axis =1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [126]:
# axis = 0이면 같은 열 안에서 정렬이 된다. (열끼리)
np.sort(arr2d, axis =0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

## index 를 반환하는 argsort

In [130]:
arr2d = np.array([[5,6,7,8],
                 [4,3,2,1], 
                 [10,9,12,11]])
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [128]:
# 열 정렬( 왼쪽 -> 오른쪽)
np.argsort(arr2d, axis =1) # 인덱스를 의미 

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]], dtype=int64)

## numpy 를 이용한 행렬 연산

In [134]:
# 행렬의 덧셈
a = np.array([[1,2,3],
             [3,4,5]])

In [136]:
b = np.array([[3,4,5],
             [1,2,3]])

In [137]:
a+b

array([[4, 6, 8],
       [4, 6, 8]])

In [138]:
# np.sum
a = np.array(np.arange(1,26)).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [139]:
# 같은 열데이터 간 덧셈 
np.sum(a, axis = 0)

array([55, 60, 65, 70, 75])

In [140]:
# 같은 행데이터 간 덧셈
np.sum(a, axis = 1) 

array([ 15,  40,  65,  90, 115])

In [141]:
# 행렬의 뺄셈은 생략

In [143]:
# 행렬의 곱셈
a = np.array([[1,2,3],
             [3,4,5]])

In [144]:
b = np.array([[3,4,5],
             [1,2,3]])

In [145]:
a.shape, b.shape # 튜플로 봄

((2, 3), (2, 3))

In [146]:
# 아다마르 곱 (배열의 사이즈가 같아야 함 덧셈처럼)
# 같은 위치의 값을 곱함
a*b 

array([[ 3,  8, 15],
       [ 3,  8, 15]])

In [148]:
a = np.array(np.arange(1,10)).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [150]:
b = np.array(np.arange(1,7)).reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [151]:
a.shape, b.shape # (3,3) , (3,2) = > 안에 3,3 이 같아야 곱해지고 결과는 (3,2) 가 나옴

((3, 3), (3, 2))

In [153]:
# 행렬의 곱셈 표현 1
np.dot(a,b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [154]:
# 행렬의 곱셈 표현 2
a.dot(b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

## Broadcasting

In [155]:
a = np.array([[1,2,3],
             [3,4,5]])

In [156]:
b = np.array([[3,3,3],
             [3,3,3]])

In [157]:
a+b

array([[4, 5, 6],
       [6, 7, 8]])

In [158]:
# broadcasting 연산
a+3

array([[4, 5, 6],
       [6, 7, 8]])

In [159]:
a-3

array([[-2, -1,  0],
       [ 0,  1,  2]])

In [160]:
# 아다마르곱
a*3

array([[ 3,  6,  9],
       [ 9, 12, 15]])

In [161]:
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.        , 1.33333333, 1.66666667]])

In [162]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [163]:
b = np.array([[1],
             [2]])

In [164]:
a.shape , b.shape

((2, 3), (2, 1))

In [165]:
# 행 단위로 broadcasting 연산
a * b

array([[ 1,  2,  3],
       [ 6,  8, 10]])

In [166]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [167]:
b = np.array([1,2,3])

In [168]:
# 열 단위로 broadcasting 연산
a * b

array([[ 1,  4,  9],
       [ 3,  8, 15]])